#define ALL_INTERCOMS          -1
#define INTERCOM_DISCONNECTED   0
#define INTERCOM_RX_ONLY        1
#define INTERCOM_TX_ONLY        2
#define INTERCOM_RX_AND_TX      3
#define INTERCOM_DEFAULT_VOLUME 1

#define STATION_INTERCOM_CONFIGURATION_INDEX  0
#define STATION_INTERCOM_UNIT_INDEX           1
#define STATION_RACKS_CONFIGURATION_INDEX     2

#define INTERCOM_STATIONSTATUS_HASINTERCOMACCESS  0
#define INTERCOM_STATIONSTATUS_CONNECTION         1
#define INTERCOM_STATIONSTATUS_VOLUME             2
#define INTERCOM_STATIONSTATUS_LIMITED            3
#define INTERCOM_STATIONSTATUS_TURNEDOUTALLOWED   4
#define INTERCOM_STATIONSTATUS_FORCEDCONNECTION   5
#define INTERCOM_STATIONSTATUS_VOICEACTIVATION    6
#define INTERCOM_STATIONSTATUS_MASTERSTATION      7
