#define ALL_INTERCOMS          -1
#define INTERCOM_DISCONNECTED   0
#define INTERCOM_RX_ONLY        1
#define INTERCOM_TX_ONLY        2
#define INTERCOM_RX_AND_TX      3
#define INTERCOM_DEFAULT_VOLUME 1

#define INTERCOM_STATIONSTATUS_HASINTERCOMACCESS  "hasAccess"
#define INTERCOM_STATIONSTATUS_CONNECTION         "connection"
#define INTERCOM_STATIONSTATUS_VOLUME             "volume"
#define INTERCOM_STATIONSTATUS_LIMITED            "isLimited"
#define INTERCOM_STATIONSTATUS_TURNEDOUTALLOWED   "turnedOutAllowed"
#define INTERCOM_STATIONSTATUS_FORCEDCONNECTION   "forcedConnection"
#define INTERCOM_STATIONSTATUS_VOICEACTIVATION    "voiceActivation"
#define INTERCOM_STATIONSTATUS_MASTERSTATION      "masterStation"
#define INTERCOM_STATIONSTATUS_WIREDRACKS         "wiredRacks"
