name: Extensions

on:
  pull_request:
    paths:
    - 'extensions/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Build
      shell: cmd
      run: |
        cd extensions/vcproj64
        cmake .. && cmake --build .
    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: acre2_extensions-${{ matrix.os }}-debug
        path: extensions/build
